// Code generated by apicli. DO NOT EDIT.

package main

import (
	"github.com/hnhuaxi/appcli/env"
	"github.com/hysios/mx/impl"
)

var Injects = map[string]interface{}{}

var InjectFuncs = map[string]interface{}{
	"listenServer": impl.ListenServer,
	"newGateway":   impl.NewGateway,
}

var InjectTypes = map[string]interface{}{}

func init() {
	env.Injects(Injects)
	env.InjectTypes(InjectTypes)
	env.InjectFuncs(InjectFuncs)

}
